package com.abien.wisdomator;

import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 *
 * @author adam-bien.com
 */
@ApplicationPath("resources")
public class RESTConfig extends Application{

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(com.abien.wisdomator.business.security.boundary.AccessLocalExceptionMapper.class);
        resources.add(com.abien.wisdomator.business.security.boundary.SecurityExceptionMapper.class);
        resources.add(com.abien.wisdomator.business.wisdom.boundary.WisdomResource.class);
        return resources;
    }
    
}
